<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>ECW Software</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap" rel="stylesheet">
    <link rel="icon" type="image/x-icon" href="assets/img/ecw2.jpg" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" />
    <style>
    @page {
        margin-top: 25mm;
        margin-right: 10mm;
        margin-bottom: 20mm;
        margin-left: 10mm;
    }

    body {
        margin: 0;
        font-family: sans-serif;
        font-size: 10px;
    }

    header {
        position: fixed;
        top: -38mm;
        left: -20;
        right: 0;
        height: 20mm;
    }

    footer {
        position: fixed;
        bottom: -25mm;
        left: 0;
        right: 0;
        height: 25mm;
        text-align: center;
        line-height: 13px;
        border-top: 2px solid #000;
    }

    .content {
        margin-bottom: 5mm;

    }

    table {
        width: 100%;
        border-collapse: collapse;
        table-layout: fixed;

    }

    tbody td. {
        border: 0.5px solid #000;
        padding: 5px 2px;
        font-size: 9px;
    }

    tfoot th. {
        border: 0.5px solid #000;
        padding: 5px 2px;
        font-size: 9px;
    }

    thead th. {
        border: 0.5px solid #000;
        padding: 5px 2px;
        font-size: 9px;
    }



    thead th {
        background-color: #cf1349;
        color: #fff;
        text-align: center;
    }

    thead {
        display: table-header-group;
    }

    tr {
        page-break-inside: avoid;
    }

    /* .datatable_td {
        padding: 3px;
        border-top: 1.5px solid #000;
        border-bottom: 1.5px solid #000;
    } */

    .datatable_data_td {
        padding: 1px 3px;
        line-height: 1.2;
    }

    .page-break {
        page-break-after: always;
    }

    .header_th {
        text-align: left;
        height: 20px;
        line-height: 0.8rem;
        padding: 0;
        font-weight: 400;
    }
    </style>
</head>


<body>
    <table style="position: fixed; top: -20mm;">
        <tr>
            <th rowspan="2" style="width:10%;">
                <img style="height:60px;" src="<?php echo base_url() ?>assets/img/logo-icon.png" />
            </th>
            <th style="width:90%;font-size:18px;font-weight:500;text-align:center;">
                <span>Invoice Summary Report</span>
            </th>
            <th rowspan="2" style="width:10%;"></th>
        </tr>
        <tr>
            <th style="width:90%;text-align:center; font-size:10px; padding-top:0px;">
                <?php if (!empty($date_from) && !empty($date_to)): ?>
                <small>From <?= htmlspecialchars($date_from) ?> to <?= htmlspecialchars($date_to) ?></small>
                <?php else: ?>
                <?php endif; ?>
            </th>
        </tr>
    </table>

    <table>
        <tr>
            <?php
            date_default_timezone_set('Asia/Colombo');

            $session_user = '';
            if (isset($this->session)) {
                $session_user = $this->session->userdata('name')
                             ?? $this->session->userdata('username')
                             ?? $this->session->userdata('user')
                             ?? $this->session->userdata('emp_no')
                             ?? '';
                if (is_array($session_user)) {
                    $session_user = reset($session_user);
                }
            } elseif (session_status() === PHP_SESSION_ACTIVE) {
                $session_user = $_SESSION['name'] ?? $_SESSION['username'] ?? $_SESSION['user'] ?? $_SESSION['emp_no'] ?? '';
            }

            $display_user = $session_user !== '' ? htmlspecialchars($session_user) : 'Unknown User';
            ?>
            <td style="width:65%;" class="footer_text">
                This report is generated by <?= $display_user ?> at <?= date('Y-m-d H:i:s') ?>
            </td>
        </tr>
    </table>
    <footer>
        <table>
            <tr>

            </tr>
            <tr>
                <td style="width:65%;" class="footer_text">Edirisingha Cushion Works (Pvt) Ltd</td>
                <td style="width:20%;text-align:center;" class="footer_text"></td>
                <td style="width:20%;text-align:right;" class="footer_text">ECW Software</td>
            </tr>
            <tr>
                <td class="footer_text">Nittambuwa</td>
                <td style="text-align:center;" class="footer_text"></td>
            </tr>
            <tr>
                <td colspan="3" class="footer_text" style="letter-spacing: 2.8px; text-align:center;">
                    SOUTH ASIA'S LARGEST INTERIOR MODIFICATION CENTER
                </td>
            </tr>
        </table>
    </footer>


    <?php
    $total_gross = 0;
    $total_vat = 0;
    $total_net = 0;
    foreach ($report as $row) {
        $total_gross += $row['Gross Total'] ?? 0;
        $total_vat += $row['Vat Amount'] ?? 0;
        $total_net += $row['Invoice Net Amount'] ?? 0;
    }
    ?>

    <table style="border: 1px solid #000;">
        <thead>
            <tr>
                <th style="text-align: left; width:12%;">Invoice Date</th>
                <th style="text-align: left; width:12%;">Invoice No</th>
                <th style="text-align: left; width:12%;">Jobcard No</th>
                <th style="text-align: left; width:15%;">Customer Name</th>
                <th style="text-align: left; width:12%;">Tax Number</th>
                <th style="text-align: right; width:12%;">Gross Amount</th>
                <th style="text-align: right; width:12%;">Tax Amount</th>
                <th style="text-align: right; width:13%;">Invoice Net Amount</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($report as $row): ?>
            <tr>
                <td style="text-align: left; "><?= htmlspecialchars($row['Date'] ?? '') ?></td>
                <td style="text-align: left; "><?= htmlspecialchars($row['Invoice No'] ?? 0, 2) ?></td>
                <td style="text-align: left; "><?= htmlspecialchars($row['Jobcard No'] ?? 0, 2) ?></td>
                <td style="text-align: left; "><?= htmlspecialchars($row['Customer Name'] ?? 0, 2) ?></td>
                <td style="text-align: left; "><?= htmlspecialchars($row['Vat Number'] ?? 0, 2) ?></td>
                <td style="text-align: right; "><?= number_format($row['Gross Total'] ?? 0, 2) ?></td>
                <td style="text-align: right; "><?= number_format($row['Vat Amount'] ?? 0, 2) ?></td>
                <td style="text-align: right; "><?= number_format($row['Invoice Net Amount'] ?? 0, 2) ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
        <tfoot>
            <tr>
                <th colspan="5" style="text-align: right;">Total Amount</th>
                <th style="text-align: right; background-color: #cce5ff"><?= number_format($total_gross ?? 0, 2) ?></th>
                <th style="text-align: right; background-color: #cce5ff"><?= number_format($total_vat ?? 0, 2) ?></th>
                <th style="text-align: right; background-color: #cce5ff"><?= number_format($total_net ?? 0, 2) ?></th>
            </tr>
        </tfoot>
    </table>
</body>

</html>